package com.java.beans;

import java.util.Date;
 abstract public class Accounts {

	private String Id,name,mobile;
	private int pin, balance, count;
	
	
 public	Accounts(){
		
		this.Id=null;
		this.mobile=null;
		this.name=null;
		this.pin=0;
		this.balance=0;
		count++;
		
	}
	
public String Autogenerated_Id(String name) {
	
	
	String st ="";
	st +="10002304"+name.substring(3)+count+new Date().getYear();
	
	
	return "";
}
 
 
 
public	Accounts( String mobile, String name, int pin,int b){
			
 	    this.name=name;
 	    this.Id=Autogenerated_Id(name);
		this.mobile=mobile;
		this.pin=pin;
		this.balance=b;
		count++;
		
	}


public String getId() {
	return Id;
}
public String getName() {
	return name;
}

public String getMobile() {
	return mobile;
}


public int getPin() {
	return pin;
}

public void setId(String id) {
	Id = id;
}
public void setMobile(String mobile) {
	this.mobile = mobile;
}
public void setName(String name) {
	this.name = name;
}
public void setPin(int pin) {
	this.pin = pin;
}


public void setBalance(int balance) {
	this.balance = balance;
}
public int getBalance() {
	return balance;
}
@Override
public String toString() {
	// TODO Auto-generated method stub
	return super.toString();
}
public abstract void Savings();
public abstract void Dematacc();	
	

	
	
}
